services:
  node:
    image: tuhinsu/node:lts
    restart: unless-stopped
    container_name: office-celebration.test
    user: root
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host --port 80"